dist: trusty
sudo: false
language: python
cache: pip

matrix:
  include:
    - env: TOXENV=py26
      python: 2.6
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py34
      python: 3.4
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py37
      python: 3.7

branches:
  only:
    - master

install:
  - pip install coverage tox

script:
  - coverage run --source=geomark $(command -v tox)

after_success:
  coveralls
